using System.Text;

namespace HapticDrive.Simagic.PHPR.Research.Inventory;

public static class SimagicDeviceInventorySummaryFormatter
{
    public const string SafetyBanner = """
        STAGE 2G READ-ONLY SAFETY
        This tool performs inventory only: no output reports, no feature writes, no vibration commands,
        no P-HPR commands, and no SimPro Manager / SimHub control.
        """;

    public static string FormatConsole(
        SimagicDeviceInventorySnapshot snapshot,
        string? jsonPath = null,
        string? markdownPath = null)
    {
        ArgumentNullException.ThrowIfNull(snapshot);

        var builder = new StringBuilder();
        builder.AppendLine("Simagic P700 / P-HPR inventory summary");
        builder.AppendLine($"Discovered at UTC: {snapshot.DiscoveredAtUtc:O}");
        builder.AppendLine($"Read-only methods: {FormatList(snapshot.Methods.Select(method => method.ToString()))}");
        builder.AppendLine($"Inventory items: {snapshot.DeviceCount:N0}");
        builder.AppendLine($"Specific Simagic candidates: {snapshot.SpecificSimagicCandidates.Count:N0}");
        builder.AppendLine($"Generic HID/USB candidates: {snapshot.GenericHidOrUsbCandidates.Count:N0}");
        builder.AppendLine($"P700 candidates: {snapshot.P700Candidates.Count:N0}");
        builder.AppendLine($"P-HPR/module-controller candidates: {snapshot.PHprCandidates.Count:N0}");
        builder.AppendLine($"Discovery errors: {snapshot.Errors.Count:N0}");

        foreach (var item in snapshot.SpecificSimagicCandidates.Take(12))
        {
            builder.AppendLine($"- {item.CandidateKind}: {item.DisplayName} ({FormatVendorProduct(item)}), score {item.CandidateScore}; {item.CandidateReason}");
        }

        if (snapshot.SpecificSimagicCandidates.Count == 0)
        {
            builder.AppendLine("No Simagic-specific local candidates were observed. Real P700/P-HPR identity remains awaiting user-provided inventory.");
        }

        if (snapshot.Errors.Count > 0)
        {
            builder.AppendLine("Errors:");
            foreach (var error in snapshot.Errors)
            {
                builder.AppendLine($"- {error.Method}: {error.Message}");
            }
        }

        if (!string.IsNullOrWhiteSpace(jsonPath))
        {
            builder.AppendLine($"Sanitized JSON export: {jsonPath}");
        }

        if (!string.IsNullOrWhiteSpace(markdownPath))
        {
            builder.AppendLine($"Sanitized Markdown export: {markdownPath}");
        }

        builder.AppendLine("P-HPR visibility is not validated by tooling alone; modules may appear only through the P700 controller.");
        return builder.ToString();
    }

    public static string FormatMarkdown(SimagicDeviceInventorySnapshot snapshot)
    {
        ArgumentNullException.ThrowIfNull(snapshot);

        var sanitized = SimagicDeviceInventorySanitizer.SanitizeSnapshot(snapshot);
        var builder = new StringBuilder();
        builder.AppendLine("# Simagic Device Inventory Summary");
        builder.AppendLine();
        builder.AppendLine("Generated by Stage 2G read-only inventory tooling.");
        builder.AppendLine();
        builder.AppendLine("## Safety");
        builder.AppendLine();
        builder.AppendLine("- Read-only inventory only.");
        builder.AppendLine("- No output reports.");
        builder.AppendLine("- No feature writes.");
        builder.AppendLine("- No vibration commands.");
        builder.AppendLine("- No P-HPR commands.");
        builder.AppendLine("- No SimPro Manager or SimHub control.");
        builder.AppendLine();
        builder.AppendLine("## Status");
        builder.AppendLine();
        builder.AppendLine($"- Discovered at UTC: `{sanitized.DiscoveredAtUtc:O}`");
        builder.AppendLine($"- Items: `{sanitized.DeviceCount:N0}`");
        builder.AppendLine($"- Methods: `{FormatList(sanitized.Methods.Select(method => method.ToString()))}`");
        builder.AppendLine($"- Specific Simagic candidates: `{sanitized.SpecificSimagicCandidates.Count:N0}`");
        builder.AppendLine($"- Generic HID/USB candidates: `{sanitized.GenericHidOrUsbCandidates.Count:N0}`");
        builder.AppendLine($"- Errors: `{sanitized.Errors.Count:N0}`");
        builder.AppendLine();

        builder.AppendLine("## Candidate Inventory");
        builder.AppendLine();
        builder.AppendLine("| Candidate | Score | Display name | VID/PID | Method | Reason | Safe instance |");
        builder.AppendLine("| --- | ---: | --- | --- | --- | --- | --- |");
        foreach (var item in sanitized.Items.Where(item => item.CandidateKind != SimagicDeviceCandidateKind.Unknown).Take(100))
        {
            builder.Append("| ");
            builder.Append(Escape(item.CandidateKind.ToString()));
            builder.Append(" | ");
            builder.Append(item.CandidateScore);
            builder.Append(" | ");
            builder.Append(Escape(item.DisplayName));
            builder.Append(" | ");
            builder.Append(Escape(FormatVendorProduct(item)));
            builder.Append(" | ");
            builder.Append(Escape(item.DiscoveryMethod.ToString()));
            builder.Append(" | ");
            builder.Append(Escape(item.CandidateReason));
            builder.Append(" | ");
            builder.Append(Escape(item.SafeInstanceId ?? item.SafeDevicePath ?? "not available"));
            builder.AppendLine(" |");
        }

        if (sanitized.Items.All(item => item.CandidateKind == SimagicDeviceCandidateKind.Unknown))
        {
            builder.AppendLine("| Unknown | 0 | No candidate inventory observed | not available | not available | Real device inventory awaiting user data | not available |");
        }

        builder.AppendLine();
        builder.AppendLine("## Errors");
        builder.AppendLine();
        if (sanitized.Errors.Count == 0)
        {
            builder.AppendLine("No read-only discovery errors were captured.");
        }
        else
        {
            foreach (var error in sanitized.Errors)
            {
                builder.AppendLine($"- `{error.Method}`: {error.Message}");
            }
        }

        builder.AppendLine();
        builder.AppendLine("## P-HPR Visibility Note");
        builder.AppendLine();
        builder.AppendLine("P-HPR modules may not appear as separate USB/HID devices. They may be exposed only through the P700 pedal controller. Treat any P-HPR visibility claim as unknown until Device Manager / USBView / tool output is validated.");
        return builder.ToString();
    }

    private static string FormatList(IEnumerable<string> values)
    {
        var items = values.Where(value => !string.IsNullOrWhiteSpace(value)).Distinct().ToArray();
        return items.Length == 0 ? "none" : string.Join(", ", items);
    }

    private static string FormatVendorProduct(SimagicDeviceInventoryItem item)
    {
        return item.VendorId is null || item.ProductId is null
            ? "VID/PID not available"
            : $"VID_{item.VendorId:X4}/PID_{item.ProductId:X4}";
    }

    private static string Escape(string value)
    {
        return value.Replace("|", "\\|", StringComparison.Ordinal);
    }
}
