namespace HapticDrive.Asio.Core.Audio;

public sealed record AudioOutputStatus(
    AudioOutputDeviceKind Kind,
    AudioOutputDeviceState State,
    string DisplayName,
    string StatusMessage,
    string? DeviceName,
    int SampleRate,
    int ChannelCount,
    int BufferSize,
    bool RequiresPhysicalHardware,
    bool IsManualDebugOnly,
    bool IsAvailable,
    bool IsHardwareArmed = false,
    int? SelectedOutputChannel = null,
    int? DeviceOutputChannelCount = null,
    long SubmittedBufferCount = 0,
    long DroppedBufferCount = 0,
    long RenderCallbackCount = 0,
    long BackendCallbackCount = 0,
    long UnderrunCount = 0,
    bool IsStreaming = false,
    TimeSpan? LastRenderDuration = null,
    TimeSpan? MaximumRenderDuration = null,
    TimeSpan? LastCallbackJitter = null,
    TimeSpan? MaximumCallbackJitter = null,
    TimeSpan? LastTelemetryAge = null,
    string? LastError = null);
