namespace HapticDrive.Asio.Core.Haptics;

public sealed record HapticTelemetrySignals(
    float? SpeedMetersPerSecond,
    float? Throttle,
    float? Brake,
    float? Steer,
    int? Gear,
    int? SuggestedGear,
    int? EngineRpm,
    int? IdleRpm,
    int? MaxRpm,
    int? MaxGears,
    bool? TractionControlActive,
    bool? AntiLockBrakesActive,
    HapticWheelSignals<byte>? SurfaceTypeIds,
    HapticWheelSignals<SurfaceKind>? SurfaceKinds,
    HapticWheelSignals<float>? TyreSlip,
    HapticWheelSignals<float>? TyreSlipAngle,
    HapticWheelSignals<float>? WheelSpeedMetersPerSecond,
    HapticWheelSignals<float>? SuspensionVelocity,
    HapticWheelSignals<float>? SuspensionAcceleration,
    HapticWheelSignals<float>? WheelVerticalForce,
    HapticWheelSignals<float>? BrakeTemperatureCelsius,
    float? VerticalG,
    HapticEventSignals? Event);
