namespace HapticDrive.Asio.Audio.Effects;

public sealed record SlipEffectOptions(
    bool IsEnabled,
    bool WheelSlipEnabled,
    float WheelSlipGain,
    float WheelSlipFrequencyHz,
    float WheelSlipNoiseAmount,
    bool WheelLockEnabled,
    float WheelLockGain,
    float WheelLockFrequencyHz,
    float WheelLockNoiseAmount,
    float MinimumSpeedKph,
    float FullIntensitySpeedKph,
    float SlipRatioThreshold,
    float SlipRatioFullScale,
    float SlipAngleThresholdRadians,
    float SlipAngleFullScaleRadians,
    float TriggerThrottle,
    float TriggerBrake,
    float LowPedalInputMultiplier,
    float AssistedSlipMultiplier,
    float BrakeLockSlipRatioThreshold,
    float BrakeLockWheelSpeedRatioThreshold,
    float MaximumAmplitude,
    TimeSpan ResponseSmoothingTime,
    uint MaximumTelemetryFrameLag)
{
    public static SlipEffectOptions Default { get; } = new(
        IsEnabled: true,
        WheelSlipEnabled: true,
        WheelSlipGain: 0.09f,
        WheelSlipFrequencyHz: 52f,
        WheelSlipNoiseAmount: 0.18f,
        WheelLockEnabled: true,
        WheelLockGain: 0.10f,
        WheelLockFrequencyHz: 68f,
        WheelLockNoiseAmount: 0.24f,
        MinimumSpeedKph: 8f,
        FullIntensitySpeedKph: 90f,
        SlipRatioThreshold: 0.08f,
        SlipRatioFullScale: 0.45f,
        SlipAngleThresholdRadians: 0.08f,
        SlipAngleFullScaleRadians: 0.45f,
        TriggerThrottle: 0.1f,
        TriggerBrake: 0.1f,
        LowPedalInputMultiplier: 0.35f,
        AssistedSlipMultiplier: 0.75f,
        BrakeLockSlipRatioThreshold: 0.35f,
        BrakeLockWheelSpeedRatioThreshold: 0.35f,
        MaximumAmplitude: 0.2f,
        ResponseSmoothingTime: TimeSpan.FromMilliseconds(18),
        MaximumTelemetryFrameLag: 120);
}

public readonly record struct SlipEffectSnapshot(
    bool IsEnabled,
    bool WheelSlipEnabled,
    bool WheelLockEnabled,
    bool IsActive,
    float CurrentSlipIntensity,
    float CurrentLockIntensity,
    float CurrentSlipRatio,
    float CurrentSlipAngleRadians,
    float CurrentMinimumWheelSpeedRatio,
    float CurrentFrequencyHz,
    float CurrentNoiseAmount,
    float CurrentAmplitude,
    string ActiveSource,
    string ActiveReason,
    float PeakLevel);
